#!/bin/bash
cd ${0%/*} || exit 1

./Allclean

if [ -z "$WM_PROJECT_VERSION" ]; then
  if [ -f "/opt/openfoam240/etc/bashrc" ]; then
    . /opt/openfoam240/etc/bashrc
  elif [ -f "$WM_PROJECT_DIR/etc/bashrc" ]; then
    . "$WM_PROJECT_DIR/etc/bashrc"
  fi
fi

blockMesh &> log.bolckMesh

decomposePar &> log.decomposePar

NPROCS=${NPROCS:-32}
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

mpirun --allow-run-as-root --mca btl self,tcp  -np "$NPROCS" lammpsFoam -parallel &> log.parallel
