#!/bin/bash
cd ${0%/*} || exit 1

./Allclean

if [ -z "$WM_PROJECT_VERSION" ]; then
  if [ -f "/opt/openfoam240/etc/bashrc" ]; then
    . /opt/openfoam240/etc/bashrc
  elif [ -f "$WM_PROJECT_DIR/etc/bashrc" ]; then
    . "$WM_PROJECT_DIR/etc/bashrc"
  fi
fi

blockMesh

lammpsFoam &> log.run